/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

import { FormControlProps } from '@bit/mui-org.material-ui.form-control/dist/src/FormControl/index';
export { FormControlProps };