/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

import { FormHelperTextProps } from '@bit/mui-org.material-ui.form-helper-text/dist/src/FormHelperText/index';
export { FormHelperTextProps };