/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

import { OutlinedInputProps } from '@bit/mui-org.material-ui.outlined-input/dist/src/OutlinedInput/index';
export { OutlinedInputProps };